[package]
name = "npc"
version.workspace = true
edition.workspace = true

[[bin]]
name = "lhsc"
path = "src/main.rs"

[dependencies]
np_syntax = { path = "../np_syntax" }
np_hir = { path = "../np_hir" }
np_eval = { path = "../np_eval" }
np_codegen = { path = "../np_codegen" }
lhs_jit = { path = "../lhs_jit" }
lhs_mem = { path = "../lhs_mem" }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
